### ISSUE TITLE
Inconsistency between the dataset and the loading method

### ISSUE THREAD

**Issue by savkov** [qipeng/gcn-over-pruned-trees#1]
In two places accessing tokens from the tacred dataset ([here](https://github.com/yuhaozhang/tacred-relation/blob/9d0a38bee69f16b2276d52ae2b259aa114cb2017/data/loader.py#L43) and [here](https://github.com/yuhaozhang/tacred-relation/blob/master/prepare_vocab.py#L78) the wrong key has been used. The data in this repository uses `tokens` instead of `token` as the key for the list of tokens. This looks like a typo that has been corrected as a previous [project](https://github.com/yuhaozhang/tacred-relation/blob/master/dataset/tacred/train.json) had what would have worked with this code, namely `token`, as the key.

I've fixed the code for myself but you may decide whether to fix the code or the data.

P.S. thanks for your code, which is otherwise quite nice and tidy! ☺️

**Comment by yuhaozhang** [comment]
Hi @savkov, this is indeed a mistake in the generation of the sample data. Thanks for capturing this! The issue has now been fixed.

And glad that you find the code useful!
