### ISSUE TITLE
Speedup training 10 times by one line of code

### ISSUE THREAD

**Issue by wzhouad** [qipeng/gcn-over-pruned-trees#11]
Hi Yuhao,
The code looks very well written, but it's kind of slow. I found that you are doing all tree manipulations on GPU. Just add
```python
head, words, subj_pos, obj_pos = head.cpu().numpy(), words.cpu().numpy(), subj_pos.cpu().numpy(), obj_pos.cpu().numpy()
```
at line 77 in gcn.py, then the speed increases from 0.12 sec/batch to 0.016 sec/batch on my machine.

**Comment by yuhaozhang** [comment]
Hi @wzhouad,

Indeed! Thanks for finding this! Do you mind making a PR to the code to fix this? I can merge your PR into the master branch afterwards.

p.s. Are you using LSTM at the bottom when you compare the speed improvement? I think if LSTM is used, the bottleneck should become the LSTM operations and less speed improvement should be observed?
