### ISSUE TITLE
A little confuse on the code in func. head_to_tree in tree.py

### ISSUE THREAD

**Issue by AaronWhite95** [qipeng/gcn-over-pruned-trees#14]
In the code: https://github.com/qipeng/gcn-over-pruned-trees/blob/db7c128e5c6fcccbe56c1358ba8f4fed30428678/model/tree.py#L80
I wonder whether this loop is a dead loop?
For example: if h = 3, head[2] = 3, then it gonna loop with adding '2' into tmp and never stop.
Cause that's the problem on my dataset, so I wonder if this method has a problem?
Thank you

**Comment by ZohaibRamzan** [comment]
> In the code:
> 
> https://github.com/qipeng/gcn-over-pruned-trees/blob/db7c128e5c6fcccbe56c1358ba8f4fed30428678/model/tree.py#L80
> 
> 
> I wonder whether this loop is a dead loop?
> For example: if h = 3, head[2] = 3, then it gonna loop with adding '2' into tmp and never stop.
> Cause that's the problem on my dataset, so I wonder if this method has a problem?
> Thank you

Can you tell me what was the problem? 
I am working on my dataset and facing MemoryError issue at this point.

**Comment by iiyuwan** [comment]
I am facing the same issue, do you know how to solve it ? thank you very much. @ @HWZX @ZohaibRamzan
