### ISSUE TITLE
Missing a line with the no-attn in train.py

### ISSUE THREAD

**Issue by savkov** [qipeng/gcn-over-pruned-trees#2]
There is a line missing [here](https://github.com/qipeng/gcn-over-pruned-trees/blob/master/train.py#L38) that should have added the `--no-attn` key. I copied it from [here](https://github.com/yuhaozhang/tacred-relation/blob/master/train.py#L38) for myself.

**Comment by yuhaozhang** [comment]
Hi @savkov, I am a bit confused. The GCN model in this repo does not have any form of attention mechanism in it. Why do you need a `--no-attn` argument in the training script? Did the training code break without this key?

**Comment by savkov** [comment]
I was copying the training command from the wrong repo and then tried to fix that. But you're right, it does make sense for it not to be there. Thanks and sorry for the confusion.

**Comment by yuhaozhang** [comment]
Ok that makes sense. Closing this issue.
