### ISSUE TITLE
eval.py error

### ISSUE THREAD

**Issue by pencoa** [qipeng/gcn-over-pruned-trees#3]
When I run eval.py, an error raised.

    Loading model from saved_models/00/best_model.pt
    [ Fail: model loading failed. ]
    Traceback (most recent call last):
      File "eval.py", line 35, in <module>
        opt = torch_utils.load_config(model_file)
      File "/home/penzm/gcn-over-pruned-trees/utils/torch_utils.py", line 161, in load_config
        return dump['config']
    UnboundLocalError: local variable 'dump' referenced before assignment

**Comment by pencoa** [comment]
My pytorch version is 0.4.1.post2 and Python 3.6.5

**Comment by yuhaozhang** [comment]
Hi @pencoa, this error message often suggests that pytorch cannot find the saved model file in the specified directory. Do you have `saved_models/00/best_model.pt` in the directory?

**Comment by pencoa** [comment]
em, yes. I have check the saved model directory.
![image](https://user-images.githubusercontent.com/7123063/46883650-582b3900-ce85-11e8-8c19-ccae428ea0da.png)
In the morning, I thought it was a problem of global variable. But there is no variable with the same name dump in torch_utils.py. 
After then, I test torch.load in the root directory using jupyter, it failed with memory error. 
Maybe I should run eval.py with CUDA specified upfront.

**Comment by pencoa** [comment]
Wow, it works. 
![image](https://user-images.githubusercontent.com/7123063/46884797-abeb5180-ce88-11e8-9853-81f45023c1ed.png)

**Comment by pencoa** [comment]
@yuhaozhang  Thank you for your elegant code.

**Comment by yuhaozhang** [comment]
@pencoa Glad that you figured out the issue!
